language: node_js
cache: yarn
node_js:
  - '7'
before_script:
  - npm run bootstrap
script:
  - npm run build
  - npm run check
# after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
